/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package memo1.ejercicio1;

    public class Main {
        public static void main(String[] args) {
            // Crear una instancia de Account usando el constructor sin argumentos
            Account account1 = new Account();
            // Configurar los valores para la cuenta
            account1.setCbu(123456789L);
            account1.setBalance(1000.0);

            // Crear una instancia de Account usando el constructor con el saldo inicial
            Account account2 = new Account(500.0);
            // Configurar el CBU para la segunda cuenta
            account2.setCbu(987654321L);

            // Imprimir detalles de las cuentas para verificar
            System.out.println("Cuenta 1:");
            System.out.println("CBU: " + account1.getCbu());
            System.out.println("Balance: " + account1.getBalance());

            System.out.println("Cuenta 2:");
            System.out.println("CBU: " + account2.getCbu());
            System.out.println("Balance: " + account2.getBalance());
        }
    }
